name: base
channels:
  - defaults
  - conda-forge
  - plotly
dependencies:
  - ipykernel
  - matplotlib
  - numpy
  - scipy
  - sympy
  - scikit-learn
  - plotly
  - pandas
  - nbformat
# variables:
#   VAR1: valueA
#   VAR2: valueB